Feature/my page
AYU-CAMPUS/AYU-FE pull request #2
Opened 2022-10-14 18:01 UTC by dlantjdgkgk

## Description

- 마이페이지 마크업 구현입니다. 

## Commits

- 버튼 클릭에 따른 기능 구현 전 마크업만 구현 해놓은 상태입니다.

## Note

- 편하게 피드백 주시면 감사하겠습니다.

2022-10-16 16:57 UTC, BonhaengLee requested changes
리뷰 달았습니다. 확인부탁드립니다.
추후 수정 예정(주석이나 코멘트 기록) or 수정 or 설명(유지) 등으로 진행하심 될 것 같습니다.

2022-10-16 16:57 UTC, BonhaengLee commented on .eslintrc.js
> +    // "@typescript-eslint/no-explicit-any": "error",
여기 주석처리한 이유가 궁금합니다.

2022-10-16 16:57 UTC, BonhaengLee commented on .eslintrc.js
> +    "jsx-a11y/label-has-associated-control": [
이 rule이 들어간 이유가 궁금합니다.

2022-10-16 16:57 UTC, BonhaengLee commented on components/MyPage/MyPageDataList/DataList.tsx
> +      <div className="dataInfo">
Styled를 가장 바깥 태그에서만 사용하고 내부는 태그마다 스타일을 입힌건가요? styled를 사용하기 때문에 className에 BEM같은 네이밍 컨벤션을 쓰지 않아도 된다는 장점이 생기는데 이렇게 되면 className을 어떻게 이름지을지 계속 고민해야되서 장점이 사라진다고 생각했습니다.

2022-10-16 16:57 UTC, BonhaengLee commented on components/MyPage/MyPageInfo/DownloadData.tsx
> +  createData(
const rows = [ { subject : 'XXX', dataName: 'YYY', writer: 'ZZZ' }, { subject : 'XXX2', dataName: 'YYY2', writer: 'ZZZ2' }]로 넣으시려고 한 것 같은데 바로 객체 리터럴로 만들어 넣어도 되지 않았을까 싶습니다. 밑에서 사용할 때 '이무성', '특수교육학개론', '특수교육학개론....'라고 인수 목록을 차례대로 createData 함수에 전달해주고 있는데 이렇게 전달하면 객체리터럴로 바로 넣어주는 것보다 객체의 어떤 키에 뭘 넣어주는지(순서를 꼭 맞춰 넣어줘야 하는) 혼란이 클 것이라고 느꼈습니다. createData이지만 정확히 어떤 Data인지에 대해서도 헷갈릴 수 있다고 생각합니다.

2022-10-16 16:57 UTC, BonhaengLee commented on components/MyPage/MyPageInfo/DownloadData.tsx
> +              <TableRow key={row.subject}>
Table에 들어오는 데이터가 예상되지 않지만 row에 subject를 key로 넣어주는 경우 subject가 겹치는 경우는 없을까요? 있다면 각 item별로 id를 만들어 그걸 key로 넣어주는 게 나을 수도 있어서 여쭤봅니다.

2022-10-16 16:57 UTC, BonhaengLee commented on components/MyPage/MyPageInfo/ExchangeAcceptance.tsx
> +            {dataStatus ? (
dataStatus라 하면 어떤 상태를 의미하는 것 같은데 상태가 맞다면 당장 setState는 필요없으니 const [dataStatus] = useState(false)와 같이 만들어두면 좀더 괜찮지 않을까 싶습니다.

2022-10-16 16:57 UTC, BonhaengLee commented on components/MyPage/MyPageInfo/MyInformation.tsx
> +                pattern: /[가-힣ㄱ-ㅎㅏ-ㅣ]/gi,
이런 정규식 패턴같은 경우에 constants 같은 파일을 하나 만들어서 상수를 몰아두면 좋을 것 같습니다. 일단 정규표현식 자체가 가독성이 매우 안 좋아서 영어로라도 어떤 패턴이구나 알아보게 하면 좋겠습니다.

2022-10-16 16:57 UTC, BonhaengLee commented on components/MyPage/MyPageInfo/MyPageInfo.tsx
> +// import { useForm, SubmitHandler } from "react-hook-form";
주석 처리하는 경우 그냥 삭제해도 될듯 합니다.

2022-10-16 16:57 UTC, BonhaengLee commented on components/MyPage/MyPageInfo/types.ts
> +export interface IUserFormInput {
UserForm에 이 입력들은 필수적이지 않나요? optional(!)로 되어 있어서 설명 부탁드립니다.

2022-10-16 16:57 UTC, BonhaengLee commented on components/MyPage/MyPageNav/MyPageNav.tsx
> +    window.history.replaceState("", "", `/mypage?value=${menu}`);
window.history.replaceState가 같은 페이지 내에서 다른 컴포넌트로 이동시킬 때 history를 쌓는 용도인 것 같은데 https://kyounghwan01.github.io/blog/React/next/same-page-stack-history/#%E1%84%80%E1%85%A2%E1%84%8B%E1%85%AD 이 방식이랑 동작이 같나요?

2022-10-16 16:57 UTC, BonhaengLee commented on utils/hookFormUtil.ts
> +export const FormErrorMessages = {
문자열을 상수로 정리한 방식이 좋은 것 같습니다.

2022-10-16 16:59 UTC, BonhaengLee commented on components/MyPage/MyPageInfo/types.ts
> +export interface IUserFormInput {
이 케이스는 기능 구현시 보완이 된다면 문제가 없긴 합니다

2022-10-18 07:58 UTC, 0xEF6AE commented on .eslintrc.js
> +    // "@typescript-eslint/no-explicit-any": "error",
하나 타입 에러 해결이 안돼서 올렸었는데 다시 주석 풀었습니다. 타입 오류 해결하고 pr 날리겠습니다.

2022-10-18 09:54 UTC, dlantjdgkgk commented on .eslintrc.js
> +    "jsx-a11y/label-has-associated-control": [
A form label must be associated with a control.eslint(jsx-a11y/label-has-associated-control) 이 오류가 label 태그 이용할 때 떠서 오류 해결하려고 rule 추가했었습니다.

2022-10-18 09:54 UTC, dlantjdgkgk commented on components/MyPage/MyPageDataList/DataList.tsx
> +      <div className="dataInfo">
앗 넵 이 부분 다 수정하겠습니다.

2022-10-18 10:01 UTC, dlantjdgkgk commented on components/MyPage/MyPageInfo/DownloadData.tsx
> +  createData(
넵 이 부분 수정하였습니다.

2022-10-18 10:02 UTC, dlantjdgkgk commented on components/MyPage/MyPageInfo/DownloadData.tsx
> +              <TableRow key={row.subject}>
일단 목 데이터로 간단하게 만들어놓은거라 id 값은 고려 안했었네요. 수정하였습니다.

2022-10-18 10:11 UTC, dlantjdgkgk commented on components/MyPage/MyPageInfo/types.ts
> +export interface IUserFormInput {
제가 헷갈렸던 것 같습니다. 수정했습니다.

2022-10-18 10:25 UTC, dlantjdgkgk commented on components/MyPage/MyPageInfo/ExchangeAcceptance.tsx
> +            {dataStatus ? (
넵!

2022-10-18 11:36 UTC, dlantjdgkgk commented on components/MyPage/MyPageNav/MyPageNav.tsx
> +    window.history.replaceState("", "", `/mypage?value=${menu}`);
이제 버튼에 따라 데이터가 변경 되고 url도 변경 되는데 이 코드가 없으면 뒤로 가기 버튼을 눌렀을 때 메인 페이지로 넘어가는 게 아니라 전에 눌렀던 버튼 url로 넘어가기 때문에 메인 페이지로 넘어가지가 않아서 뒤로 가기 버튼을 눌렀을 때 메인 페이지로 넘어가게 하기 위해서 이렇게 코드를 작성하였습니다.

2022-11-20 12:00 UTC, merged